@extends('layouts_frontend._main')

@section('content')
<section class="similar-songs-section">
	<div class="container-fluid">
		<div class="section-title">
			<h2>Catalog</h2>
		</div>
		<table id="tables" class="table-bordered table-striped table-hover table" width="100%">
			<thead>
				<tr>
					<td>No</td>
					<td>Nama</td>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>1</td>
					<td>dsadasd</td>
				</tr>
				<tr>
					<td>1</td>
					<td>dsadasd</td>
				</tr>
				<tr>
					<td>1</td>
					<td>dsadasd</td>
				</tr>
				<tr>
					<td>1</td>
					<td>dsadasd</td>
				</tr>
				<tr>
					<td>1</td>
					<td>dsadasd</td>
				</tr>
				<tr>
					<td>1</td>
					<td>dsadasd</td>
				</tr>
				<tr>
					<td>1</td>
					<td>dsadasd</td>
				</tr>
				<tr>
					<td>1</td>
					<td>dsadasd</td>
				</tr>
				<tr>
					<td>1</td>
					<td>dsadasd</td>
				</tr>
				<tr>
					<td>1</td>
					<td>dsadasd</td>
				</tr>
				<tr>
					<td>1</td>
					<td>dsadasd</td>
				</tr>
			</tbody>
		</table>
	</div>
</section>
@endsection